# Generated by Django 4.0.2 on 2022-02-19 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(max_length=1000, verbose_name='Content')),
                ('priority', models.IntegerField(default=3, verbose_name='Priority')),
                ('time_create', models.TimeField(auto_now=True, verbose_name='Time Create')),
                ('time_update', models.TimeField(auto_now_add=True, verbose_name='Time Update')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
                ('priority', models.IntegerField(default=3, verbose_name='Priority')),
                ('time_create', models.TimeField(auto_now=True, verbose_name='Time Create')),
                ('time_update', models.TimeField(auto_now_add=True, verbose_name='Time Update')),
                ('is_pyblished', models.BooleanField(default=True, verbose_name='Published')),
                ('todo_pull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todo', verbose_name='Todo')),
            ],
            options={
                'verbose_name': 'TodoList',
                'verbose_name_plural': 'TodoLists',
                'ordering': ['pk'],
            },
        ),
    ]
