# Generated by Django 4.0.2 on 2022-02-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todolist_color_alter_todolist_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='is_pyblished',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='color',
            field=models.CharField(default='Red', max_length=255, verbose_name='Color'),
        ),
    ]
